"""
Module Registry
This module defines the registry of all modules in the Promethios system.
"""
from pydantic import BaseModel, Field
from typing import List, Optional

class ModuleEntry(BaseModel):
    """Module entry in the registry."""
    name: str = Field(..., description="Name of the module")
    category: str = Field(..., description="Category of the module")
    status: str = Field(..., description="Status of the module (active, planned, or scaffolded)")

class ModuleRegistry(BaseModel):
    """Module registry containing all modules in the system."""
    modules: List[ModuleEntry] = Field(default_factory=list, description="List of all modules")

# Initialize the module registry
MODULE_REGISTRY = ModuleRegistry(modules=[
    ModuleEntry(name="agents/memory_agent.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/agent.py", category="API Router", status="active"),
    ModuleEntry(name="api/agent/builder.py", category="API Router", status="active"),
    ModuleEntry(name="api/agent/memory.py", category="API Router", status="active"),
    ModuleEntry(name="api/agent/memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/agent/ops.py", category="API Router", status="active"),
    ModuleEntry(name="api/agent/planner.py", category="API Router", status="active"),
    ModuleEntry(name="api/agent/planner.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/agent/research.py", category="API Router", status="active"),
    ModuleEntry(name="api/agent_status.py", category="API Router", status="active"),
    ModuleEntry(name="api/control.py", category="API Router", status="active"),
    ModuleEntry(name="api/delegate_route.py", category="API Router", status="active"),
    ModuleEntry(name="api/delegate_route.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/delegate_stream.py", category="API Router", status="active"),
    ModuleEntry(name="api/delegate_stream.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/goals.py", category="API Router", status="active"),
    ModuleEntry(name="api/logs.py", category="API Router", status="active"),
    ModuleEntry(name="api/memory.py", category="API Router", status="active"),
    ModuleEntry(name="api/memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/memory_viewer.py", category="API Router", status="active"),
    ModuleEntry(name="api/memory_viewer.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/modules/agent.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/modules/agent_context.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/modules/delegate.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/delegate.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/modules/feedback.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/modules/memory_engine.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/modules/observer.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/orchestrator.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/plan.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/modules/plan.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/modules/plan_models.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="api/modules/project.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/project_summary.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/respond.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/respond.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/modules/stream.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/system.py", category="API Router", status="active"),
    ModuleEntry(name="api/modules/system.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/modules/user_context.py", category="API Router", status="active"),
    ModuleEntry(name="api/orchestrator/chain.py", category="API Router", status="active"),
    ModuleEntry(name="api/orchestrator/consult.py", category="API Router", status="active"),
    ModuleEntry(name="api/orchestrator/scope.py", category="API Router", status="active"),
    ModuleEntry(name="api/orchestrator/start_project.py", category="API Router", status="active"),
    ModuleEntry(name="api/orchestrator/status.py", category="API Router", status="active"),
    ModuleEntry(name="api/project/start.py", category="API Router", status="active"),
    ModuleEntry(name="api/projects/projects.py", category="API Router", status="active"),
    ModuleEntry(name="api/respond.py", category="API Router", status="active"),
    ModuleEntry(name="api/streaming_route.py", category="API Router", status="active"),
    ModuleEntry(name="api/streaming_route.py", category="Agent Module", status="active"),
    ModuleEntry(name="api/system_routes.py", category="API Router", status="active"),
    ModuleEntry(name="api/task/status.py", category="API Router", status="active"),
    ModuleEntry(name="core/agent_coordinator.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/agent_registry.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/agent_registry_enhanced.py", category="Agent Module", status="active"),
    ModuleEntry(name="core/agent_registry_enhanced.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/agent_router.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/boot.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/confidence_retry.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/error_logger.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/escalation_manager.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/forge.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/input_gateway.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/input_router.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/memory_api_quota_guard.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/memory_context_reviewer.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/memory_manager.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/nudge_manager.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/orchestrator.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/planner_agent_enhancer.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/planner_orchestrator.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/prompt_manager.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/rationale_logger.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/run.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/seeding.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/self_evaluation.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/shared_memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/task_persistence.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/task_state_manager.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/task_tagger.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/tool_router.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="core/vector_memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="db/memory_db.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="fallbacks/fix_hal_routes.py", category="Agent Module", status="active"),
    ModuleEntry(name="memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="memory/__init__.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="memory/project_memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/agent_fallback.py", category="Agent Module", status="active"),
    ModuleEntry(name="modules/agent_reflect.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/agent_reflection.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/core_beliefs_integration.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/delegate.py", category="Agent Module", status="active"),
    ModuleEntry(name="modules/drift_monitor.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/hal_memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/hal_memory_patch.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/historian_drift_report.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/live_memory_inspection.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/logic_loader.py", category="Agent Module", status="active"),
    ModuleEntry(name="modules/loop.py", category="Agent Module", status="active"),
    ModuleEntry(name="modules/memory_block_writer.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/memory_embed.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/memory_recall.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/memory_summarize.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/memory_summarizer.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/memory_summarizer_project.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/memory_thread.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/memory_writer.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/orchestrator_contract_integration.py", category="Agent Module", status="active"),
    ModuleEntry(name="modules/orchestrator_drift_integration.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/orchestrator_memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/orchestrator_memory_enhanced.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/passive_reflection.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/plan/__init__.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/plan/execute_chain.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/plan/scope.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/plan_generate.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/planning_logic_integration.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/recursive_reflection_engine.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/reflect.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/reflection_fatigue_scoring.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/reflection_grader.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/reflection_guardrails.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/reflection_styler.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/register_all_agents.py", category="Agent Module", status="active"),
    ModuleEntry(name="modules/summary_realism_scorer.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/symbolic_memory_encoder.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="modules/trust_score_evaluator.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/core_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/debugger_routes.py", category="API Router", status="active"),
    ModuleEntry(name="routes/drift_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/drift_routes_router.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/health_monitor_routes.py", category="API Router", status="active"),
    ModuleEntry(name="routes/historian_routes.py", category="API Router", status="active"),
    ModuleEntry(name="routes/memory_api_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/memory_embed_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/memory_recall_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/memory_router.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/memory_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/orchestrator_contract_routes.py", category="Agent Module", status="active"),
    ModuleEntry(name="routes/orchestrator_plan_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/plan_generate_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/reflection_router.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/reflection_routes.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="routes/self_routes.py", category="API Router", status="active"),
    ModuleEntry(name="routes/status_debug.py", category="API Router", status="active"),
    ModuleEntry(name="schemas/drift_schema.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="schemas/memory.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="schemas/memory_embed_schema.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="schemas/memory_recall_schema.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="schemas/memory_schema.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="schemas/plan_generate_schema.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="system/checklist_engine.py", category="Agent Module", status="active"),
    ModuleEntry(name="utils/reflection_analyzer.py", category="Reflection/Memory/Core", status="active"),
    ModuleEntry(name="validators/memory_retry_logic_checker.py", category="Reflection/Memory/Core", status="active"),
])

# For backward compatibility, also provide the modules as a list
MODULE_LIST = MODULE_REGISTRY.modules
