name: System Integrity Check

on:
  push:
    branches: [ main ]
  schedule:
    # Run once per day at midnight UTC
    - cron: '0 0 * * *'

jobs:
  system-health-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run system integrity tests
      run: |
        pytest tests/test_system_integrity.py -v
        
    - name: Report test results
      if: always()
      run: |
        echo "System Integrity Test Results" >> $GITHUB_STEP_SUMMARY
        echo "----------------------------" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ All system integrity tests passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ System integrity tests failed. See test output for details." >> $GITHUB_STEP_SUMMARY
        fi
